### ISSUE TITLE
ЛР часть 2 

### ISSUE THREAD

**Issue by alexandr-kaa** [ssshnabel/RTS_Shn#5]
makefile нерабочий
![изображение](https://user-images.githubusercontent.com/63350411/235344568-b53934fa-2799-406f-b404-a025fa3fd2a0.png)

**Comment by ssshnabel** [comment]
Исправила

**Comment by alexandr-kaa** [comment]
![изображение](https://user-images.githubusercontent.com/63350411/235789764-ee734e43-b84d-4cdf-b42d-e088c4fc8161.png)

**Comment by ssshnabel** [comment]
> ![изображение](https://user-images.githubusercontent.com/63350411/235789764-ee734e43-b84d-4cdf-b42d-e088c4fc8161.png)

Исправила
